title: The Star System
description: An investigation on successful actors and their impact on movie ratings
show_downloads: true
markdown: GFM
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
navigation:
  - title: introduction
    url: introduction
  - title: Rich-get-Richer
    url: rgr
