#theme: jekyll-theme-dinky
title: The Star System
description: An investigation of actors' impact on movie ratings
markdown: GFM
show_downloads: True
navigation:
  - title: Home
    url: home
  - title: Introduction
    url: introduction
  - title: What is IMDb?
    url: imdb
  - title: Rich-get-Richer Mechanism
    url: rgr
  - title: Confounding factors
    url: confounders
  - title: Observational Study
    url: observational_study
remote_theme: pages-themes/dinky@v0.2.0
plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
