title: Cayman Docs
description: Cayman-Docs is a clean, responsive theme for GitHub Pages based documentation.
show_downloads: true
theme: jekyll-theme-cayman
navigation:
  name_over_title: true
  strip_par: true
  sanitize: true
  h_max: 3
